server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: stu_web
  registry:
    address: zookeeper://192.168.82.104:2181
  consumer:
  #关闭所有服务的启动时检查
    check: false
    timeout: 10000
    retries: 3