server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.82.103:3306/class_database
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: class_service
  registry:
    address: zookeeper://192.168.82.104:2181

  protocol:
    port: -1
